### ISSUE TITLE
Can't find element

### ISSUE THREAD

**Issue by SrMilton** [GermanAizek/webdriverxx#17]
Chrome/program crashing when i try to FindElement..

>```c++
>Element email = gc.FindElement(ByName("emailOrPhone")); 
>```

Edit: same with firefox

**Comment by GermanAizek** [comment]
![](https://i.pinimg.com/originals/ab/05/1d/ab051d6b4f97dcc392567736d978c1a4.jpg)

**Comment by SrMilton** [comment]
Just happen when i use selenium beta :(

**Comment by GermanAizek** [comment]
@SrMilton,
I'm busy tonight, trying to find mistakes tomorrow.

**Comment by GermanAizek** [comment]
@SrMilton 
I made out a given oen old bug, he is bound because then the first developer made castoms shared_ptr and he is non-safe threads.
Fixing that bug will take a long time, since you need to completely replace Shared custom with standard C++ std::shared_ptr.

**Comment by GermanAizek** [comment]
@SrMilton and @MaGicSuR,
Problem I fixed, new patch tested in firefox debian 10.
I looked for a problem in the code for a long time, it turned out that the server simply did not return the status value in the json file. Thank you so much for finding the bugs.

Commit: https://github.com/GermanAizek/webdriverxx/commit/f961b67a1cc9a50865e4d931fdfbcc1e319aa07b

**Comment by GermanAizek** [comment]
![](https://thumbs.gfycat.com/TotalFrigidDutchshepherddog-size_restricted.gif)

**Comment by GermanAizek** [comment]
@SrMilton,
Answer, please, did I fix the bug?

**Comment by SrMilton** [comment]
@GermanAizek sorry man, i have no time to test this now. Be patient 😄 :x..
